Select MANGANH, TENNGANH From dbo.NGANH

SELECT TENLOP, KHOAHOC FROM dbo.LOP
 
EXEC sp_help 'SINHVIEN';

SELECT MASV, HOTEN, GT, NGAYSINH, DIACHI FROM dbo.SINHVIEN WHERE MANGANH = ''
 
Select MANGANH, KHOAHOC From dbo.LOP

INSERT INTO SINHVIEN (MANGANH, MALOP, MASV, HOTEN, NGAYSINH, GT, DIACHI) 
Values ( N'','','',N'','',N'',N'')
 
SELECT MANGANH, MALOP FROM dbo.SINHVIEN

SELECT MAGV, TK, PASS, TEN, SDT FROM dbo.LG